
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NAME NUMBER OPERATOR PARENTHESES\n    expression : expression OPERATOR expression\n    \n    expression : factor\n    \n    factor : NAME\n    \n    factor : NUMBER\n    \n    factor : PARENTHESES expression PARENTHESES\n    '
    
_lr_action_items = {'NAME':([0,5,6,],[3,3,3,]),'NUMBER':([0,5,6,],[4,4,4,]),'PARENTHESES':([0,2,3,4,5,6,7,8,9,],[5,-2,-3,-4,5,5,9,-1,-5,]),'$end':([1,2,3,4,8,9,],[0,-2,-3,-4,-1,-5,]),'OPERATOR':([1,2,3,4,7,8,9,],[6,-2,-3,-4,6,6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,6,],[1,7,8,]),'factor':([0,5,6,],[2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression OPERATOR expression','expression',3,'p_expression_factor_operator','main.py',65),
  ('expression -> factor','expression',1,'p_expression_factor','main.py',72),
  ('factor -> NAME','factor',1,'p_factor_name','main.py',79),
  ('factor -> NUMBER','factor',1,'p_factor_number','main.py',86),
  ('factor -> PARENTHESES expression PARENTHESES','factor',3,'p_factor_grouped','main.py',101),
]
